### ISSUE TITLE
Cazador bestias

### ISSUE THREAD

**Issue by MjDelmuth** [Phoenix-Core/PhoenixCore#137]
Bugtracker: https://www.wowfenix.net/bugtracker/report/459
Fecha: 12/05/2018
Creado por: Robkill

El problema: Los cazadores bestia tienen los poderes bug que la pet mata de un golpe

¿Cómo debería funcionar? ya estuvo asi antes y vuelve a lo mismo? todos los cazas horda aprovechan como si nada los bugs.. Sera que pueden hacer algo o un gm lo hace a proposito.

¿Cómo se reproduce el problema?
Todos los cazas horda ahora son bestias para aprovechar bug. Es enserio!!

**Comment by MjDelmuth** [comment]
Creado por: Cambiar personaje
pffffffff otro llorón, hay macros para activar todos los poderes al mismo tiempo y hacer un gran daño con la pet por si no sabes, aquí les dejo un videito de un caza que jugó en el wow oficial de blizzard cuando era 335a con caza bestias , en el vide juega las 3 clases , puntería, bestias y supervivencia, les dejo el link :

https://www.youtube.com/watch?v=G_m9hwU75No&feature=youtu.be&t=3m48s

Posdata: si te matan es porque eres un manco. 15/05/2018 02:53:09

**Comment by MjDelmuth** [comment]
Creado por: Cambiar personaje
por cierto el pala que demora en matar es porque es pala heal 15/05/2018 02:54:39

**Comment by MjDelmuth** [comment]
Creado por: Robkill
a gran daño dice bugear y matar de dos golpes jajaja ni un caza refull 284 o war mata asi ... y si eso no es bug xq solo los caza horda la usan y en ali ninguno.. mejor callese bugero 23/05/2018 20:58:49

**Comment by MjDelmuth** [comment]
Creado por: Cambiar personaje
naaaaa, he presentado un vídeo de muestra (que es de la ali por cierto :) ), tu solo dices tu queja como niñita llorando sin relevancia de que solo y únicamente la horda hace bug si fuera ese el caso tanto ali como horda lo hacen , por que también veo ali en bestias, , encima dices que un GM lo hace a propósito, la verdad nomas brother la queja de un manquito nomas.
P.D.: no se bugear, soy nuevo en el server y he empezado desde cero con mi unico pj. 25/05/2018 00:41:11

**Comment by Kyanv** [comment]
Solucionado, ahora irá mucho mejor el daño de las mascotas.
