### ISSUE TITLE
Conflagrar

### ISSUE THREAD

**Issue by MjDelmuth** [Phoenix-Core/PhoenixCore#151]
Bugtracker: https://www.wowfenix.net/bugtracker/report/500
Fecha: 10/06/2018
Creado por: Jordy

El problema:
El skill como iba estaba de maravillas, Lo que sucede es que al roug que le hacen este daño fue hecho por un brujo montado en un demoledor de asedio el cual por alguna razon aumenta el skill de los caster, no es por que va bug el skill.
¿Cómo debería funcionar?
69% de base de imolar y llama de sombra + un 40% de daño extra
https://subefotos.com/ver/?7cb7eae1fafab0462c8e8949bf198b08o.jpg#codigos
(con todo mi set llego a pegar 953 critico)
https://subefotos.com/ver/?a3f32262929899852a8a734b5950b8fco.jpg#codigos
69% + 40%
https://subefotos.com/ver/?a1c7e6f71bd35cd8bc660b74d67e08a6o.jpg#codigos
193 (48 absor)

¿Cómo se reproduce el problema?
https://www.wowfenix.net/bugtracker/report/492
Ocurre por no saber que ir montado en un demoledor de consquita aumenta el daño en caster en general

**Comment by MjDelmuth** [comment]
Creado por: Jordy
Carro de playa de ancestro, corregido 10/06/2018 22:46:49

**Comment by MjDelmuth** [comment]
Creado por: Cambiar personaje
si conflagrar debería estar pegando de 4k a 8k según gs poder de hechizo etc 
Ademas si sabiendo del bug del carro ustedes como caster deberían a ver reportado eso se considera aprovechamiento de bug 04/12/2018 15:28:29

**Comment by Nanatzu** [comment]
No está bug, funciona actualmente.
