### ISSUE TITLE
1000 fragmentos de vigilante de piedra

### ISSUE THREAD

**Issue by MjDelmuth** [Phoenix-Core/PhoenixCore#168]
Bugtracker: https://www.wowfenix.net/bugtracker/report/568
Fecha: 26/08/2018
Creado por: Mantius

El problema: Al momento de despojar o recibir fragmentos de vigilante de piedra mediante las misiones semanales diarias de conquista de invierno el contador en el logro no aumenta!! presento unas imágenes para que lo puedan apreciar!!!
https://ibb.co/cJxmnp
https://ibb.co/h8crL9
https://ibb.co/esw7tU
https://ibb.co/cU4ML9

¿Cómo debería funcionar?
Al recibir la recompensa de fragmentos de vigilante de piedra debería sumar en el contador del logro!!

¿Cómo se reproduce el problema?
No aumenta la cuenta cada que recibes fragmentos de vigilante de piedra el marcador del contador no aumenta se queda en el miso valor!!!!

**Comment by Kyanv** [comment]
No es bug, en el juego es totalmente distinto un despojo a obtener algo de misión. Es totalmente distinto.
