### ISSUE TITLE
Exterminación

### ISSUE THREAD

**Issue by MjDelmuth** [Phoenix-Core/PhoenixCore#18]
Bugtracker: https://www.wowfenix.net/bugtracker/report/104
Fecha: 30/01/2018
Creado por: Megadet
Enlace: https://www.wowcenter.net/?spell=63156 

El problema: buenas noches el problema es que el talento de [Exterminación] esta bug no da 40% que reduce el lanzamiento de fuego de alma esta bug arreglenlo xfavor ese es el dps del brujo demoniologia 

¿Cómo debería funcionar?

¿Cómo se reproduce el problema?

**Comment by MjDelmuth** [comment]
Hola! 
Éste tema lo expliqué a detalle en este post https://www.wowfenix.net/forum/viewtopic.php?f=4&t=2632 
Por favor denle una revisada, el bug existe y sólo cerraron mi post cuando el problema ya ha sido reportado en bug tracker varias veces.
Saludos! 02/06/2018 00:56:20

**Comment by Nanatzu** [comment]
No está bug, se realizaron pruebas y funciona actualmente.
