### ISSUE TITLE
Tótem Corriente de sanación

### ISSUE THREAD

**Issue by MjDelmuth** [Phoenix-Core/PhoenixCore#32]
Bugtracker: https://www.wowfenix.net/bugtracker/report/135
Fecha: 02/02/2018
Creado por: Liu
Enlace: https://www.wowcenter.net/?spell=5394 

El problema:
El totem Corriente de Sanación del chaman no sirve.

¿Cómo debería funcionar?
Debería sanar al personaje, grupo o banda, al que pertenece pero actualmente no lo hace.

¿Cómo se reproduce el problema?
cuando lo usas !!

**Comment by MjDelmuth** [comment]
Creado por: Cambiar personaje
Invoca un Tótem Corriente de sanación con 5 p. de salud a los pies del taumaturgo durante 5 min que sana a los miembros del grupo en 6 p. en un radio de 30 m cada 2 s. https://www.wowcenter.net/?spell=5394
Hay dice solo miembros del grupo por ningún lado dicen BANDA 
Si no sana a los de tu grupo estaría bug. y recuerda que en este core los totens no traspasan las paredes o columnas o losa , para sanar o ralentizar 08/03/2018 14:40:13

**Comment by Nanatzu** [comment]
No está bug, se realizaron pruebas y funciona actualmente.
