### ISSUE TITLE
La parte derecha del amuleto de Lord Valthalak

### ISSUE THREAD

**Issue by MjDelmuth** [Phoenix-Core/PhoenixCore#4]
Bugtracker: https://www.wowfenix.net/bugtracker/report/26
Fecha: 24/01/2018
Creado por: Folken
Enlace: https://www.wowcenter.net/?quest=8992 

El problema:
Usa el Blandón de Señalización para invocar al espíritu de Kormok y mátalo. Vuelve junto a Bodley en el interior de la Montaña Roca Negra con el amuleto de Lord Valthalak recompuesto y el Blandón de Señalización.
Amuleto de Lord Valthalak
Blandón de Señalización (Provisto)
*Kormok matado
Descripción
Ahora que tenemos lo que necesitamos, es hora de decidir a quién vas a invocar a continuación.

Kormok no estaba mal para un ogro, hasta que empezó a practicar la nigromancia. A partir de ahí, la cosa se puso espeluznante para cualquiera de la organización. Nadie se sorprendió cuando tomó su pieza de amuleto y regresó a su nuevo hogar, Scholomance.

Pero incluso allí, o quizás sobre todo allí, no estaba a salvo de los sicarios espectrales. Lo ejecutaron en presencia de su maestro, Ras Murmuhielo. 

¿Cómo debería funcionar?
Dentro la camara donde se halla Ras Murmuhielo https://www.wowcenter.net/?npc=10508#abilities en la estancia Scholomance, se usa el Blandón de Señalización https://www.wowcenter.net/?item=22052, para invocar al boss Kormok https://www.wowcenter.net/?npc=16118#abilities .

¿Cómo se reproduce el problema?
Al usar el item provisto Blandón de Señalización https://www.wowcenter.net/?item=22052 no invoca al boss Kormok https://www.wowcenter.net/?npc=16118#abilities

**Comment by MjDelmuth** [comment]
Creado por: Cambiar personaje
sigue bug esto. 31/05/2018 17:05:21

**Comment by MjDelmuth** [comment]
Creado por: Folken
Porfavor si no van a reparar la mision, siquiera pongan al NPC objetivo como lo hicieron con el Corcel Xorothiano de la mision final para la montura del brujo. 06/09/2018 11:13:41

**Comment by Nanatzu** [comment]
Duplicado [3](https://github.com/Phoenix-Core/PhoenixCore/issues/3)
