### ISSUE TITLE
Toshley

### ISSUE THREAD

**Issue by MjDelmuth** [Phoenix-Core/PhoenixCore#5]
Bugtracker: https://www.wowfenix.net/bugtracker/report/31
Fecha: 24/01/2018
Creado por: Cambiar personaje
Enlace: http://es.wowhead.com/npc=21691/toshley#english-comments 

El problema: antes este npc daba las misiones para realizar , PERO ahora no da ninguna y tampoco funcionan de los npc cercanos las misiones. no cuenta con pre-requisitos para hacerla siempre ha sido libre. 

intente hacer la quest que lleva de enlace al npc pero tambien esta BUG no la da. 
-¿Dónde se han metido esos malditos gnomos? (del Comandante Cielosombra) http://es.wowhead.com/quest=10580/donde-se-han-metido-esos-malditos-gnomos#comments

ya no da ninguna bug
-¡Gnomas piedad! http://es.wowhead.com/quest=10675/gnomas-piedad
-A lomos del relámpago http://es.wowhead.com/quest=10657/a-lomos-del-relampago
-Atrapar la Luz fantástica http://es.wowhead.com/quest=10674/atrapar-la-luz-fantastica
-Recoger transformadores de energía http://es.wowhead.com/quest=10584/recoger-transformadores-de-energia

¿Cómo debería funcionar?
deberia ser libre y obtenerla. o por medio de la mision de enlace al npc http://es.wowhead.com/quest=10580/donde-se-han-metido-esos-malditos-gnomos#comments

¿Cómo se reproduce el problema?

El NPC Toshley no da ningun quest esta bug y tmb los npc cercanos a el. y tambien la mison de enlace esta bug http://es.wowhead.com/quest=10580/donde-se-han-metido-esos-malditos-gnomos#comments

**Comment by Nanatzu** [comment]
Problema solucionado, el NPC funciona correctamente.
