### ISSUE TITLE
Salva

### ISSUE THREAD

**Issue by MjDelmuth** [Phoenix-Core/PhoenixCore#69]
Bugtracker: https://www.wowfenix.net/bugtracker/report/228
Fecha: 18/02/2018
Creado por: Daves
Enlace: https://www.wowcenter.net/?spell=34074 

El problema:
El aspecto no regenera mana cuando se combina con la habilidad "Salva" (https://www.wowcenter.net/?spell=58434). 
¿Cómo debería funcionar?
Debe regenera mana igual al 4% del mana base por CADA objetivo en el que se aplique.
¿Cómo se reproduce el problema?
Cuando se combina el aspecto con la habilidad Salva, solo regenera el mana correspondiente al daño sobre un solo objetivo, independientemente de que hayan mas objetivos afectados por el zonal de la Salva.

**Comment by MjDelmuth** [comment]
Creado por: Cambiar personaje
Aspecto de vibora https://www.wowcenter.net/?spell=34074
El maná ganado se basa en la velocidad de tu arma a distancia. Requiere un arma a distancia
Dice bien claro ganas según la velocidad de tu arma, no es por objetivo. es por tiro. salva https://www.wowcenter.net/?spell=58434). Dispara de manera continua una salva de munición al área objetivo e inflige PA*0.083700+353 p. de daño Arcano a los objetivos enemigos en un radio de 8 m cada 1,00 s durante 6 seg. dice bien claro que lanza una losa salva de munición al área (1 tiro) por cada 1 segundo durante 6 segundos. en otras palabras es 1 tiro por segundo. en otras palabras entre mas rápido disparas mas rápido ganas mana. en el anterior core estuvo bugueado así que anda acostumbrándote 08/03/2018 16:33:56

**Comment by MjDelmuth** [comment]
Creado por: Shenanigan
Hola, hasta donde recuerdo. en parte el Salva si anda mal en situaciones donde se quiere combinarlo con Aspecto de Vibora.

Y es que lo que muchos cazadores en general hacian cuando se quedaban sin mana, era que usabas Aspecto de víbora + Salva, y recuperabas inmediatamente Mana debido a la cantidad de objetivos afectados por el zonal de la Salva.

Debido a que ahora esto no funciona bien, los cazadores tenemos que estar parados todo el rato, con aspecto de vibora hasta tener 100% de mana obviamente haciendo nada porque demora mucho regenerar 08/03/2018 18:18:40

**Comment by MjDelmuth** [comment]
Creado por: Cambiar personaje
Te recomiendo que te acostumbres porque esta 100% funcional 
Tanto el Aspecto de víbora y salva funcionan tal y como debe funcionar 
Te recomiendo que leas detalladamente que dice el Aspecto de víbora. https://www.wowcenter.net/?spell=34074
as una prueba con multidisparo se supone que para eso es la habilidad de disparar a 3 objetivos https://www.wowcenter.net/?spell=27021#modified-by con el aspecto de víbora. 
Mi recomendación deberías tener dos armas una full dano y otra full velocidad de ataque 
https://www.youtube.com/watch?v=eZSXTJRLrlU lee el comentario de este vídeo. 
En el core anterior Salva y aspecto víbora era un bug de beneficio, 10/03/2018 03:16:10

**Comment by MjDelmuth** [comment]
Creado por: Daves
Añado un vídeo para que se entienda mejor el caso.
https://www.youtube.com/watch?v=wARtMtMrjG0 12/03/2018 12:38:52

**Comment by MjDelmuth** [comment]
Creado por: Cambiar personaje
Asta que por fin subes el vídeo. y lo demostrare con tu propio vídeo que no esta bug.
Cuando aspecto de víbora https://www.wowcenter.net/?spell=34074 se refiere a los ataques cuerpo a cuerpo y distancia uno investiga cuales son los ataques cuerpo a cuerpo y a distancia del cazador.
Ataque automático cuerpo a cuerpo: https://www.wowcenter.net/?spell=6603 Ataca a un objetivo automáticamente cuerpo a cuerpo con un arma equipada hasta que se anula.
Ataque a distancia: https://www.wowcenter.net/?spell=75 Dispara automáticamente al objetivo hasta que se desactiva. Los ataques a distancia lanzados por un cazador tienen un 15% de velocidad de ataque aumentada.
Como puedes ver se refiere que ataca a un objetivo en especifico (focus) 
Leamos salva otra vez https://www.wowcenter.net/?spell=58434#modified-by Dispara de manera continua una salva de munición al área objetivo e inflige PA*0.083700+353 p. de daño Arcano a los objetivos enemigos en un radio de 8 m cada 1,00 s durante 6 seg.
Al referirse al área objetivo no se refiere a un objetivo npc. player , se refiere al objetivo como un área. e inflige de daño Arcano a los objetivos enemigos en un radio de 8 m cada 1,00 s durante 6 seg. al referirse a esta especificando el tipo de daño que le aran a los objetivos dentro del área.
Por eso en los 2 servidores que lanzas salva no tarjeteas a los objetivos automáticamente. porque el objetivo de salva es el área. entiende salva no hace un target a npc o player. Tu vídeo mismo te esta matando.
Busquemos otro hechizo Picadura de serpiente https://www.wowcenter.net/?spell=1978 dice lo siguiente Pica al objetivo infligiendo PA*0.2+4*15/3 p. de daño de Naturaleza durante 15 seg. Un cazador solo puede tener una picadura activa a la vez sobre un mismo objetivo. 
Al momento de referirse AL OBJETIVO especifica. Al npc. al player. al GM. al enemigo. Por eso hay un target por medio y automáticamente targeteas al objetivo. Así que no esta BUG 3/03/2018 05:23:54

**Comment by MjDelmuth** [comment]
Creado por: Cambiar personaje
No es lo mismo decir 
destruir al objetivo
Destruir al área objetivo 
Tampoco es lo mismo
Destruir al objetivo del área 
Destruir al área objetivo. 
en español se dice el área no la área ( son errores de traducción) 
Muchos confundes español y castellano (ejemplos)
Por eso que en castellano escucha a personas decir la calor http://udep.edu.pe/castellanoactual/duda-resuelta-la-calor-o-el-calor/ 
En español es el calor https://www.metro.pr/pr/blogs/2013/08/04/calor-o-calor-duda-comun-quienes-sufren.html

COMO PUEDES VER EN LAS EXPANSIONES SIGUIENTES CAMBIA SALVA (disculpen las mayúsculas) http://es.wowhead.com/spell=194386/salva

Si lo ponemos en ingles es mas fácil de entender que en español . Continuously fires a volley of ammo at the target area, causing 300 Arcane damage to enemy targets within 8 yards every second for 6 sec. 
http://www.wowhead.com/spell=22908/volley#modified-by
No es lo mismo en ingles 
at the target area
at the target of the area

Te pongo picadura de serpiente como ejemplo Stings the target, causing (100% of Spell power) Nature damage over 15 sec. Only one Sting per Hunter can be active on any one target. http://www.wowhead.com/spell=35511/serpent-sting 13/03/2018 07:40:35

**Comment by Nanatzu** [comment]
No está bug, funciona actualmente.

Tus ataques a distancia y cuerpo a cuerpo regeneran un porcentaje de tu maná base, si tienes 13766 P de maná debes regenerar 550 P de maná cada 3 s, si realizas daño con un arma a distancia que tiene 187 de daño por segundo debes generar 412 P de maná por cada golpe a distancia y cuerpo a cuerpo con arma al objetivo.
No aplica en el caso de Salva dado que es daño al área objetivo y no al objetivo. 
Daño al objetivo: daño directo a un solo jugador o NPC.
Daño al área objetivo: daño indirecto a los jugadores o NPCs en el área objetivo (Daño en Área).
