### ISSUE TITLE
Incinerar

### ISSUE THREAD

**Issue by MjDelmuth** [Phoenix-Core/PhoenixCore#79]
Bugtacker: https://www.wowfenix.net/bugtracker/report/261
Fecha: 23/02/2018
Creado por: Absul
Enlace: http://www.wowcenter.net/?spell=47838#. 

El problema:
la spell de incinerar ( http://www.wowcenter.net/?spell=47838#. ), no deja el pequeño debuf de daño (este deja un pequeño icono del mismo incinerar) y no recuerdo si es de dos segundo que infige el daño de dot, cuando el objetivo tiene Inmolar

¿Cómo debería funcionar?
Dejar el dot que hace daño cuando el objetivo tiene Inmolar.

¿Cómo se reproduce el problema?
Incinerar no deja el daño del DOT cuando el objetivo tiene INMOLAR

**Comment by Nanatzu** [comment]
No está bug, funciona actualmente.
Al estar activado inmolar incrementa el daño en 145.5 - 169 p, no debería dejar ningún debuff ni crear daño por segundo extra.
