### ISSUE TITLE
Flor de vida

### ISSUE THREAD

**Issue by MjDelmuth** [Phoenix-Core/PhoenixCore#82]
Bugtracker: https://www.wowfenix.net/bugtracker/report/264
Fecha: 24/02/2018
Creado por: Canti
Enlace: http://www.wowcenter.net/?spell=48451 

El problema:Cuando la flor de vida la stackeas por 1,2 o 3 cura bien pero cuando esta explota cura de 3k normales a 5k critico no esta curando lo que debería curar.

¿Cómo debería funcionar?al darle el stack por 1,2 o 3 debería curar muchísimo más no estancarse en 3k como lo hace ahorita 

¿Cómo se reproduce el problema?al mandar la habilidad tanto pve como pvp esta no funciona como

**Comment by MjDelmuth** [comment]
Creado por: Cambiar personaje
Mira si este vídeo del servidor oficial de Saurfang del reino unido Analiza lo si de verdad debería curar mas https://www.youtube.com/watch?v=whWeH_LHRaM 
https://www.youtube.com/watch?v=b9W3PCG-cBU Eu-Arathor
https://www.youtube.com/watch?v=tH4smnBL8eA
Y dime que opinas? 13/03/2018 23:00:09

**Comment by MjDelmuth** [comment]
Creado por: Souldarkness
quisiera saber si le darán algún arreglo a esta habilidad de el druida heal ya que ni siquiera es viable hacer arenas con druida ya que esta habilidad sigue super bug, el stackeo de la habilidad esta bien pero al explotar los stacks de la misma por 1, 2 o 3 sigue curando absolubtamente nada 20/10/2018 15:24:58

**Comment by Nanatzu** [comment]
No está bug, funciona correctamente actualmente.
