### ISSUE TITLE
Poseer

### ISSUE THREAD

**Issue by MjDelmuth** [Phoenix-Core/PhoenixCore#97]
Bugtracker: https://www.wowfenix.net/bugtracker/report/318
Fecha: 19/03/2018
Creado por: Xinz
Enlace: http://es.wowhead.com/spell=48181/poseer 

El problema:
el talento en si deberia curar el 100% del daño generado, sin embargo, este se excede con respecto a la curacion.

¿Cómo debería funcionar?
deberia sanar el 100% de daño causado al enemigo.

¿Cómo se reproduce el problema?
el talento excede en curacion con respecto al daño , regenerando mas de lo debido , mas del 200%

**Comment by MjDelmuth** [comment]
Creado por: Kronos
en vez de arreglarlo mas lo han nerfeado mejor eliminen esta clase del wow de una vez, damos verguenza en dps ya ni nos toman en cuenta en las raids a menos que dejemos ropero, piedra de res, y maldicion de lenguas. 11/11/2018 15:56:42

**Comment by Nanatzu** [comment]
No está bug, funciona actualmente.

le commentaire le plus pathétique..
